import Navbar from "@/components/core/Navbar";

export const metadata = {
    title: "Posts Page",
    description: "Generated by create next app",
  };
  
  export default function Layout({ children }) {
    return (
      <>
        <Navbar/>
        <div className="px-4 mx-auto max-w-screen-2xl">
        {children}
        </div>
          
      </>
    );
  }